version: '3'

services:
  scraper:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: modric19
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
